<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class web_admin_model extends CI_Model
{
	private $tabulation='iitism';

    function __construct()
    {
        parent::__construct();
    }

		function getFaculty($dept)
		{
						/* 20-4-19  $query=$this->db->query("
							SELECT ud.id, CONCAT_WS(' ', ud.salutation, ud.first_name, ud.middle_name, ud.last_name) as name
							FROM users AS fd
							JOIN user_details AS ud ON fd.id = ud.id
							WHERE fd.auth_id='emp' AND ud.dept_id IN (SELECT id FROM departments WHERE type='academic')
							ORDER BY name ASC ");*/
							//return $dept;exit;
							if($dept=='stu'){
							$query=$this->db->query(" SELECT ud.id, CONCAT_WS(' ', ud.salutation, ud.first_name, ud.middle_name, ud.last_name) as name
							FROM users AS fd
							JOIN user_details AS ud ON fd.id = ud.id
							WHERE fd.auth_id='stu'
							ORDER BY id desc");
						}else{
							$query=$this->db->query(" SELECT ud.id, CONCAT_WS(' ', ud.salutation, ud.first_name, ud.middle_name, ud.last_name) as name
							FROM users AS fd
							JOIN user_details AS ud ON fd.id = ud.id
							WHERE fd.auth_id='emp'
							ORDER BY id desc");
						}
						return $query->result_array();
				}

				public function getusersdetails($userid,$utype){
					if(!empty($userid) && !empty($utype)){
						if($utype=='stu'){
							$query=$this->db->query("SELECT ud.*,ebd.* FROM user_details ud JOIN stu_details ebd on ud.id=ebd.admn_no where ud.id='$userid'  group by ud.id");

						}else{
							$query=$this->db->query("SELECT ud.*,ebd.*,email.domain_name,ua.contact_no FROM user_details ud JOIN emp_basic_details ebd on ud.id=ebd.emp_no left JOIN emaildata_emp email on ud.id=email.emp_id JOIN user_address ua ON ud.id=ua.id where ud.id='$userid'  group by ud.id");

						}
					}

						return $query->result_array();
				}
				public function get_depts()
			{

				$sql="select * from departments order by name";
		            $query = $this->db->query($sql);

		            if ($this->db->affected_rows() >= 0) {
		                return $query->result();
		            } else {
		                return false;
		            }
			}
				public function checkusercount($data){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					$emp_no=$data['username'];
					$query = $this->db2->query("SELECT * FROM faculty_info WHERE emp_no ='$emp_no'");
					$cnt=$query->num_rows();
					$querymis = $this->db->query("SELECT * FROM web_faculty_info WHERE emp_no ='$emp_no'");
					$cntmis=$querymis->num_rows();
				return $cnttotal=$cnt+$cntmis;
				}
				public function getusersdetailsforedit($userid,$utype){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					if(!empty($userid) && !empty($utype)){
							$query=$this->db2->query("SELECT * FROM faculty_info where emp_no='$userid' group by emp_no");
					}
						return $query->result_array();
				}
				public function getusersprofile($auth_id){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					if(!empty($auth_id)){
							$query=$this->db2->query("SELECT * FROM faculty_info where emp_no='$auth_id' group by emp_no");
					}
						return $query->result_array();
				}
				public function updateUserProfileimg($data){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					$emp_no=$data['username'];
					$p_image=$data['file_path'];
					$p_image_mis=$data['file_path_mis'];
					if(empty($p_image)){
						$p_image="na";
							$p_image_mis="na";
					}else{
						$p_image=$data['file_path'];
						$p_image_mis=$data['file_path_mis'];
					}
					if(empty($p_image_mis)){
							$p_image_mis="na";
					}else{
						$p_image_mis=$data['file_path_mis'];
					}
					$sqlweb = "update faculty_info set photopath='$p_image_mis' where emp_no='$emp_no'";
					$savedata=$this->db2->query($sqlweb);

					$sql= "update web_faculty_info set photopath='$p_image_mis' where emp_no='$emp_no'";
					$savedata=$this->db->query($sql);
				}

				public function updateUserCV($data){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					$emp_no=$data['username'];
					$p_image=$data['file_path_cv'];
					$p_image_mis=$data['file_path_mis_cv'];
					if(empty($p_image)){
						$p_image="na";
							$p_image_mis="na";
					}else{
						$p_image=$data['file_path_cv'];
						$p_image_mis=$data['file_path_mis_cv'];
					}
					if(empty($p_image_mis)){
							$p_image_mis="na";
					}else{
						$p_image_mis=$data['file_path_mis_cv'];
					}
					$sqlweb = "update faculty_info set cv_path='$p_image' where emp_no='$emp_no'";
					$this->db2->query($sqlweb);

					$sql = "update web_faculty_info set cv_path='$p_image' where emp_no='$emp_no'";
					$this->db->query($sql);
				}

				public function updateUserPublication($data){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					$emp_no=$data['username'];
					$p_image=$data['file_path_pub'];
					$p_image_mis=$data['file_path_mis_pub'];
					if(empty($p_image)){
						$p_image="na";
							$p_image_mis="na";
					}else{
						$p_image=$data['file_path_pub'];
						$p_image_mis=$data['file_path_mis_pub'];
					}
					if(empty($p_image_mis)){
							$p_image_mis="na";
					}else{
						$p_image_mis=$data['file_path_mis_pub'];
					}

					$sqlweb = "update faculty_info set pub_path='$p_image' where emp_no='$emp_no'";
					$this->db2->query($sqlweb);

					$sql = "update web_faculty_info set pub_path='$p_image' where emp_no='$emp_no'";
					$this->db->query($sql);
				}


				public function updateUserOtherinfo($data){
					$CI = &get_instance();
					$this->db2 = $CI->load->database($this->tabulation, TRUE);
					$emp_no=$data['username'];
	   			$salutation=$data['salutation'];
					$f_name=$data['f_name'];
					$m_name=$data['m_name'];
					$l_name=$data['l_name'];
					$j_date=$data['j_date'];
					$r_date=$data['r_date'];
					$type=$data['type'];
				//	$dept=$data['dept'];
			//		$desig=$data['desig'];
					$email=$data['email'];
					$mobile=$data['mobile'];
					$landline=$data['landline'];
					$pp=$data['pp'];
					$research_interest=$data['research_interest'];

					$query = $this->db->query('SELECT name FROM departments WHERE id ="'.$data['dept'].'"');
				 foreach($query->result() as $query){$dept=$query->name;}

				 $query1 = $this->db->query('SELECT name FROM designations WHERE id ="'.$data['desig'].'"');
				 foreach($query1->result() as $querys){ $desig=$querys->name;}
				 if(empty($desig)){
					 $desig=$data['desig'];
				 }
if(empty($dept)){
	$dept=$data['dept'];
}
					$sqlweb = "update faculty_info set salutation='$salutation',first_name='$f_name' ,middle_name='$m_name' ,last_name='$l_name',dept_name='$dept'
					,designation='$desig' ,type='$type' ,email='$email',mobile_no='$mobile',office_no='$landline' ,joining_date='$j_date' ,retirement_date='$r_date',research_interest='$research_interest',per_page='$pp' where emp_no='$emp_no'";
					$this->db2->query($sqlweb);
	     #  echo $this->db2->last_query();die();
					$sql = "update web_faculty_info set salutation='$salutation',first_name='$f_name' ,middle_name='$m_name' ,last_name='$l_name',dept_name='$dept'
					,designation='$desig' ,type='$type' ,email='$email',mobile_no='$mobile',office_no='$landline' ,joining_date='$j_date' ,retirement_date='$r_date',research_interest='$research_interest',per_page='$pp' where emp_no='$emp_no'";
					$this->db->query($sql);
				}
public function saveuserinfo($data){
	//		print_r($data);
	$CI = &get_instance();
	$this->db2 = $CI->load->database($this->tabulation, TRUE);

$emp_no=$data['username'];
$salutation=$data['salutation'];
$f_name=$data['f_name'];
$m_name=$data['m_name'];
$l_name=$data['l_name'];
$usertype=$data['usertype'];
$p_image=$data['file_path'];
$p_image_mis=$data['file_path_mis'];
$email=$data['email'];
$mobile=$data['mobile'];
$landline=$data['landline'];
$j_date=$data['j_date'];
$r_date=$data['r_date'];
$pp=$data['pp'];
if(empty($p_image)){
	$p_image="na";
		$p_image_mis="na";
}else{
	$p_image=$data['file_path'];
	$p_image_mis=$data['file_path_mis'];
}
if(empty($p_image_mis)){
		$p_image_mis="na";
}else{
	$p_image_mis=$data['file_path_mis'];
}
	   	$query = $this->db->query('SELECT name FROM departments WHERE id ="'.$data['dept'].'"');
		  foreach($query->result() as $query){$dept=$query->name;}

			$query1 = $this->db->query('SELECT name FROM designations WHERE id ="'.$data['desig'].'"');
		  foreach($query1->result() as $querys){ $desig=$querys->name;}

			$sqlweb = "insert into faculty_info(emp_no, salutation, first_name, middle_name,last_name, dept_name, designation,type,photopath,email, mobile_no, office_no,joining_date, retirement_date,research_interest,per_page,cv_path, pub_path)
					values ('$emp_no','$salutation','$f_name','$m_name','$l_name','$dept','$desig','$usertype','$p_image','$email','$mobile','$landline','$j_date','$r_date','','$pp','','')";
				$savedata=$this->db2->query($sqlweb);
				#	echo $this->db2->last_query();die();
					if(!empty($savedata)){
						$sqlmis = "insert into web_faculty_info(emp_no, salutation, first_name, middle_name,last_name, dept_name, designation,type,photopath,email, mobile_no, office_no,joining_date, retirement_date,research_interest,per_page,cv_path, pub_path)
								values ('$emp_no','$salutation','$f_name','$m_name','$l_name','$dept','$desig','$usertype','$p_image_mis','$email','$mobile','$landline','$j_date','$r_date','','$pp','','')";
							$savedatamis=$this->db->query($sqlmis);
							//	echo $this->db->last_query();die();
							if(!empty($savedatamis)){
								$this->session->set_flashdata('Success' , 'User Added Successfully.');
								redirect('web_admin/web_admin/add_user');
							}else{
								$this->session->set_flashdata('Error' , 'Unable to add User.Please Try Again.');
								redirect('web_admin/web_admin/add_user');
							}

					}else{
						$this->session->set_flashdata('Error' , 'Unable to add User.Please Try Again.');
						redirect('web_admin/web_admin/add_user');
					}

	//	print_r($dept);
}
public function save_projectOpening($data){
	$CI = &get_instance();
	$this->db2 = $CI->load->database($this->tabulation, TRUE);
	$postName=$data['postName'];
	$dept=$data['dept'];
	$s_date=date('Y-m-d');//$data['s_date'];
	$e_date=$data['e_date'];
	$att_req=$data['att_req'];
	$c_person=$data['c_person'];

	if($att_req=="Yes"){
		$file_mis=$data['file_add'];
		$file_web=$data['file_add_web'];
	}else{
		$file_mis="na";
		$file_web="na";
	}
	$auth = $this->session->userdata('id');
	$name = $this->session->userdata('name');
	//echo $auth;exit;
	$sqlweb = "insert into project_opening_tbl (post, faculty_id,faculty_name,department,contact_person,start_date,end_date,file_path,archived)
			values ('$postName', '$auth', '$name','$dept','$c_person','$s_date', '$e_date', '$file_web','Y')";
		$savedata=$this->db2->query($sqlweb);
		#echo $this->db2->last_query();die();
		if(!empty($savedata)){
		//  echo "data Saved";
		$sql = "insert into web_project_opening_tbl (post, faculty_id,faculty_name,department,contact_person,start_date,end_date,file_path,archived)
				values ('$postName', '$auth', '$name','$dept','$c_person','$s_date', '$e_date', '$file_mis','Y')";
			$result= $savedata=$this->db->query($sql);
			if(!empty($result)){
				$this->session->set_flashdata('Success' , 'Project Opening Posted Successfully.');
				redirect('web_admin/web_admin/project_opening/');

			}else{
				$this->session->set_flashdata('Error' , 'Unable to Upload Project Opening 1.Please try Again');
				redirect('web_admin/web_admin/project_opening/');

			}
		}else{
					$this->session->set_flashdata('Error' , 'Unable to Upload Project Opening 2.Please try Again');
				redirect('web_admin/web_admin/project_opening/');

		}



}
public function save_userNotice($data){
	$CI = &get_instance();
	$this->db2 = $CI->load->database($this->tabulation, TRUE);

	#print_r($data);exit;
	$type=$data['type'];
	$title=$data['title'];
	$s_date=date('Y-m-d');//$data['s_date'];
	$e_date=$data['e_date'];
	$att_req=$data['att_req'];
	$link=$data['link'];
	if($att_req=="Yes"){
		$file_mis=$data['file_add'];
		$file_web=$data['file_add_web'];
	}else if($att_req=="link"){
		$file_mis=$link;
		$file_web=$link;
	}else{
		$file_mis="na";
		$file_web="na";
	}
	$auth = $this->session->userdata('id');
	//echo $auth;exit;
	$title = str_replace( array( '\'', '"', ',' , ';', '<', '>' ), ' ', $title);
	$sqlweb = "insert into article (title, body,user_id,start_date,end_date,image_path)
			values ('$title', '$type', '$auth','$s_date', '$e_date', '$file_web')";
		$savedata=$this->db2->query($sqlweb);
		#echo $this->db2->last_query();die();
		if(!empty($savedata)){
		//  echo "data Saved";
		 $sql = "insert into web_article (title, body,user_id,start_date,end_date,image_path)
	 			values ('$title', '$type', '$auth','$s_date', '$e_date', '$file_web')";
			$result= $savedata=$this->db->query($sql);
			if(!empty($result)){
				$this->session->set_flashdata('Success' , 'Notice Upload Successfully.');
				redirect('web_admin/web_admin/upload_notices/');

			}else{
				$this->session->set_flashdata('Error' , 'Unable to Upload Notice 1.Please try Again');
				redirect('web_admin/web_admin/upload_notices/');

			}
		}else{
					$this->session->set_flashdata('Error' , 'Unable to Upload Notice 2.Please try Again');
				redirect('web_admin/web_admin/upload_notices/');

		}
}
public function save_artical($data){
	//print_r($data);
	$CI = &get_instance();
	$this->db2 = $CI->load->database($this->tabulation, TRUE);
	// $data = $this->db2->query("SELECT * FROM article");
	// 	echo "<pre>";
	// 	print_r($data->result_array());
	// 	exit;

	//print_r($data);exit;

	$type=$data['type'];
	$title=$data['title'];
	$s_date=date('Y-m-d');//$data['s_date'];
	$e_date=$data['e_date'];
	$att_req=$data['att_req'];
	$link=$data['link'];
	if($att_req=="Yes"){
		$file_mis=$data['file_add'];
		$file_web=$data['file_add_web'];
	}else if($att_req=="link"){
		$file_mis=$link;
		$file_web=$link;
	}else{
		$file_mis="na";
		$file_web="na";
	}
	$auth = $this->session->userdata('id');
	//echo $auth;exit;
//$title = str_replace( array( '\'', '"', ',' , ';', '<', '>' ), ' ', $title); ori
$title = str_replace( array( '\'', '"', ',' , ';', '<', '>' ), ' ', $title);
	$sqlweb = "insert into article (title, body,user_id,start_date,end_date,image_path)
			values ('$title', '$type', '$auth','$s_date', '$e_date', '$file_web')";
		$savedata=$this->db2->query($sqlweb);
         
	#echo $this->db2->last_query();die();

		if(!empty($savedata)){
		//  echo "data Saved";
		 $sql = "insert into web_article (title, body,user_id,start_date,end_date,image_path)
	 			values ('$title', '$type', '$auth','$s_date', '$e_date', '$file_web')";
			$result= $savedata=$this->db->query($sql);
			if(!empty($result)){
				$this->session->set_flashdata('Success' , 'Notice Upload Successfully.');
				redirect('web_admin/web_admin/add_article/');

			}else{
				$this->session->set_flashdata('Error' , 'Unable to Upload Notice 1.Please try Again');
				redirect('web_admin/web_admin/add_article/');

			}
		}else{
					$this->session->set_flashdata('Error' , 'Unable to Upload Notice 2.Please try Again');
				redirect('web_admin/web_admin/add_article/');

		}
}
    function upload_notice($data){
	//  exit;
	
      $CI = &get_instance();
	  $this->db2 = $CI->load->database($this->tabulation, TRUE);
	  
	 // print_r($data);exit;
	  
      $dep=$data['dep'];
      $title=$data['title'];
    	$s_date=date('Y-m-d');//$data['s_date'];
      $e_date=$data['e_date'];

      $att_req=$data['att_req'];
      if($att_req=="Yes"){
        $file_mis=$data['file_add'];
        $file_web=$data['file_add_web'];
      }else{
        $file_mis="na";
        $file_web="na";
      }
      $auth = $this->session->userdata('id');
			//echo $auth;exit;
			$title = str_replace( array( '\'', '"', ',' , ';', '<', '>' ), ' ', $title);
      $sqlweb = "insert into notice (title, depart, e_id,s_time,e_time,path)
          values ('$title', '$dep', '$auth','$s_date', '$e_date', '$file_web')";
        $savedata=$this->db2->query($sqlweb);
        if(!empty($savedata)){
        //  echo "data Saved";
         $sql = "insert into web_notice (title, depart, e_id,s_time,e_time,path)
             values ('$title', '$dep', '$auth','$s_date', '$e_date', '$file_web')";
		  $result= $savedata=$this->db->query($sql);

		 // echo $this->db->last_query(); exit;

          if(!empty($result)){
            $this->session->set_flashdata('Success' , 'Department Notice Upload Successfully.');
            redirect('web_admin/web_admin/');

          }else{
            $this->session->set_flashdata('Error' , 'Unable to Upload Department Notice.Please try Again');
            redirect('web_admin/web_admin/');

          }
        }else{
              $this->session->set_flashdata('Error' , 'Unable to Upload Department Notice.Please try Again');
            redirect('web_admin/web_admin/');

        }
         // echo $this->db->last_query(); exit;
    }


}
?>
