<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class acc_gpf_interest_rate_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get acc_gpf_interest_rate by sn
     */
    function get_acc_gpf_interest_rate($sn)
    {
        return $this->db->get_where('acc_gpf_interest_rate',array('sn'=>$sn))->row_array();
    }
        
    /*
     * Get all acc_gpf_interest_rate
     */
    function get_all_acc_gpf_interest_rate()
    {
        $this->db->order_by('sn', 'desc');
        if($query=$this->db->get('acc_gpf_interest_rate')){
            if($query->num_rows()>0){   
                return $query->result();
            }
            else{
                return false;
            }
        }
    }
        
    /*
     * function to add new acc_gpf_interest_rate
     */
    function add_acc_gpf_interest_rate($params)
    {
        $this->db->insert('acc_gpf_interest_rate',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update acc_gpf_interest_rate
     */
    function update_acc_gpf_interest_rate($sn,$params)
    {
        $this->db->where('sn',$sn);
        return $this->db->update('acc_gpf_interest_rate',$params);
    }
    
    /*
     * function to delete acc_gpf_interest_rate
     */
    function delete_acc_gpf_interest_rate($sn)
    {
        return $this->db->delete('acc_gpf_interest_rate',array('sn'=>$sn));
    }
}
