<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class acc_itax_rate_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get acc_itax_rate by fy
     */
    function get_acc_itax_rate($sn)
    {
        return $this->db->get_where('acc_itax_rates',array('sn'=>$sn))->row_array();
    }

    /*
     * Get all acc_itax_rates
     */
    function get_all_acc_itax_rates()
    {
        $q="select atr.sn,atr.fy,(select att.description from acc_taxpayer_type att where att.id=atr.tp_type) as tp_type,atr.r_from,atr.r_to,atr.rate,atr.tax_regime from acc_itax_rates atr order by atr.fy desc";
        if($query=$this->db->query($q)){
            if($query->num_rows()>0){
                return $query->result();
            }
            else{
                return false;
            }
        }
        else{
            return false;
        }
    }

    /*
     * function to add new acc_itax_rate
     */
    function add_acc_itax_rate($params)
    {
        $this->db->insert('acc_itax_rates',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update acc_itax_rate
     */
    function update_acc_itax_rate($sn,$params)
    {
        $this->db->where('sn',$sn);
        return $this->db->update('acc_itax_rates',$params);
    }

    /*
     * function to delete acc_itax_rate
     */
    function delete_acc_itax_rate($sn)
    {
        return $this->db->delete('acc_itax_rates',array('sn'=>$sn));
    }

    function getCitizenType(){
        $q="select att.id,att.description from acc_taxpayer_type att";
        if($query=$this->db->query($q)){
            if($query->num_rows()>0){
                return $query->result();
            }
            else{
                return false;
            }
        }
        else{
            return false;
        }
    }
}
