<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Acc_taxpayer_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get acc_taxpayer_type by id
     */
    function get_acc_taxpayer_type($id)
    {
        return $this->db->get_where('acc_taxpayer_type',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all acc_taxpayer_type count
     */
    function get_all_acc_taxpayer_type_count()
    {
        $this->db->from('acc_taxpayer_type');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all acc_taxpayer_type
     */
    function get_all_acc_taxpayer_type($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('acc_taxpayer_type')->result_array();
    }
        
    /*
     * function to add new acc_taxpayer_type
     */
    function add_acc_taxpayer_type($params)
    {
        $this->db->insert('acc_taxpayer_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update acc_taxpayer_type
     */
    function update_acc_taxpayer_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('acc_taxpayer_type',$params);
    }
    
    /*
     * function to delete acc_taxpayer_type
     */
    function delete_acc_taxpayer_type($id)
    {
        return $this->db->delete('acc_taxpayer_type',array('id'=>$id));
    }
}
